import { Worker } from 'bullmq';
import { getConnection } from '../index.js';
import { getJob, getSpec, updateJobStatus, createChallenge } from '../../db/client.js';
import { getCategory } from '../../categories/index.js';

let worker = null;

/**
 * Normalize flag from spec — researcher uses `flag` (string),
 * but some legacy specs may have `flags` (array).
 */
function resolveFlag(spec) {
  if (spec.flag) return spec.flag;
  if (Array.isArray(spec.flags) && spec.flags.length > 0) return spec.flags[0];
  return null;
}

/**
 * Mock builder fallback for categories that don't have a real Claude-powered builder yet.
 * Uses the spec's actual data (flag, name, narrative, exploit path) instead of hardcoded defaults.
 */
function buildMockFallback(spec, categoryId) {
  const name = spec.challengeName || spec.challenge_name || 'Challenge';
  const flag = resolveFlag(spec) || 'Exploit3rs{n0_fl4g_1n_sp3c}';
  const narrative = spec.narrative || 'Complete the challenge.';
  const difficulty = spec.difficulty || 'medium';
  const points = spec.points || 300;
  const exploitPath = spec.exploitPath || ['Analyze the challenge', 'Find the vulnerability', 'Capture the flag'];
  const techStack = spec.techStack || [];
  const antiAi = spec.antiAiCountermeasures || [];

  const exploitSteps = exploitPath.map((step, i) => `${i + 1}. ${step}`).join('\n');
  const antiAiSection = antiAi.length > 0
    ? `\n## Anti-AI Measures\n${antiAi.map((m) => `- ${m}`).join('\n')}\n`
    : '';

  return {
    files: [
      {
        path: 'challenge.py',
        language: 'python',
        content: `#!/usr/bin/env python3
"""${name} — ${categoryId} challenge"""
# Category: ${categoryId}
# Tech stack: ${techStack.join(', ') || 'Python'}
# Difficulty: ${difficulty}

FLAG = "${flag}"

# TODO: Phase 3 will replace this with a real ${categoryId} challenge
# generated by Claude using the category-specific prompt template.
print("Challenge: ${name}")
print("Category: ${categoryId}")
print("This is a mock — real builder coming in Phase 3")
`,
      },
      {
        path: 'solve.py',
        language: 'python',
        content: `#!/usr/bin/env python3
"""Solver for ${name}"""
# Exploit path from spec:
${exploitPath.map((s, i) => `# Step ${i + 1}: ${s}`).join('\n')}

print("[*] Running solver...")
${exploitPath.map((s, i) => `print("[*] Step ${i + 1}: ${s}")`).join('\n')}
print(f"[+] Flag: ${flag}")
`,
      },
      {
        path: 'writeup.md',
        language: 'markdown',
        content: `# ${name} - Writeup

## Challenge Description
${narrative}

## Category
${categoryId}

## Difficulty
${difficulty} (${points} points)

## Tech Stack
${techStack.map((t) => `- ${t}`).join('\n') || '- Python'}

## Solution
${exploitSteps}
${antiAiSection}
## Flag
\`${flag}\`
`,
      },
    ],
    tokenUsage: 0,
    durationMs: 0,
  };
}

export function startBuilderWorker() {
  worker = new Worker(
    'build-queue',
    async (bullJob) => {
      const { jobId } = bullJob.data;
      console.log(`[Builder] Processing job ${jobId}`);

      const job = getJob(jobId);
      if (!job) {
        console.error(`[Builder] Job ${jobId} not found`);
        return;
      }

      updateJobStatus(jobId, 'building');

      const specRow = getSpec(jobId);
      const spec = specRow?.spec_json || {};

      // Resolve category from spec or job
      const categoryId = spec.category || job.category || 'web';
      const category = getCategory(categoryId);

      let buildResult;
      const startTime = Date.now();

      if (category?.builder) {
        try {
          console.log(`[Builder] Dispatching to ${categoryId} category builder`);
          const builder = (await import(`../../categories/${categoryId}/builder.js`)).default;
          buildResult = await builder.build(spec);
        } catch (err) {
          console.error(`[Builder] ${categoryId} builder failed: ${err.message}`);
          console.error(`[Builder] Falling back to mock for job ${jobId}`);
          buildResult = buildMockFallback(spec, categoryId);
        }
      } else {
        console.warn(`[Builder] No builder for "${categoryId}", using mock fallback`);
        buildResult = buildMockFallback(spec, categoryId);
      }

      const totalDurationMs = Date.now() - startTime;

      // Handle both old format (array) and new format ({ files, tokenUsage, durationMs })
      let fileManifest, tokenUsage, generationTimeMs;

      if (Array.isArray(buildResult)) {
        // Legacy format: builder returned just the file array (mock builders)
        fileManifest = buildResult;
        tokenUsage = 0;
        generationTimeMs = totalDurationMs;
      } else {
        // New format: builder returned { files, tokenUsage, durationMs }
        fileManifest = buildResult.files;
        tokenUsage = buildResult.tokenUsage || 0;
        generationTimeMs = buildResult.durationMs || totalDurationMs;
      }

      createChallenge({
        jobId,
        fileManifest,
        tokenUsage,
        generationTimeMs,
      });

      updateJobStatus(jobId, 'pending_build_review');
      console.log(`[Builder] Job ${jobId} (${categoryId}) → ${fileManifest.length} files, ${tokenUsage} tokens, ${generationTimeMs}ms`);
    },
    {
      connection: getConnection(),
      concurrency: 3,
    }
  );

  worker.on('failed', (bullJob, err) => {
    console.error(`[Builder] Job ${bullJob?.data?.jobId} failed:`, err.message);
    if (bullJob?.data?.jobId) {
      try {
        updateJobStatus(bullJob.data.jobId, 'failed', err.message);
      } catch {}
    }
  });

  console.log('[Builder] Worker started (category-dispatch mode)');
  return worker;
}

export function getBuilderWorker() {
  return worker;
}
