export default {
  id: 'web',
  name: 'Web Exploitation',
  description: 'SQL injection, XSS, SSTI, SSRF, authentication bypass, file upload, deserialization, and other web application vulnerabilities.',
  icon: 'globe',
  color: '#57cbff',
  defaultTechStack: ['Docker', 'Python', 'Flask', 'Nginx'],
  difficulties: [
    { level: 'warm_up', points: [50], estimatedMinutes: 10, description: 'Guided walkthrough, single-step vuln' },
    { level: 'easy', points: [150], estimatedMinutes: 20, description: 'Basic injection or auth bypass' },
    { level: 'medium', points: [350], estimatedMinutes: 45, description: 'Chained exploits, WAF bypass, SSTI' },
    { level: 'hard', points: [700], estimatedMinutes: 90, description: 'Complex deserialization, multi-step RCE' },
  ],
  artifactTypes: ['Dockerfile', 'docker-compose.yml', 'Application source', 'Exploit script', 'Writeup'],
  outputFiles: ['Dockerfile', 'docker-compose.yml', 'app.py', 'requirements.txt', 'exploit.py', 'writeup.md'],
  difficultyWeights: { warm_up: 50, easy: 150, medium: 350, hard: 700 },
  supportsDocker: true,
  formFields: [
    { name: 'vulnType', label: 'Vulnerability Type', type: 'select', options: ['SQL Injection', 'XSS', 'SSTI', 'SSRF', 'File Upload', 'Auth Bypass', 'Deserialization', 'Path Traversal', 'Command Injection', 'IDOR', 'XXE', 'Prototype Pollution', 'Other'] },
    { name: 'framework', label: 'Target Framework', type: 'select', options: ['Flask', 'Express.js', 'Django', 'Spring', 'Laravel', 'WordPress', 'Custom'] },
    { name: 'hasWAF', label: 'Include WAF', type: 'checkbox', default: false },
    { name: 'hasAuth', label: 'Requires Authentication', type: 'checkbox', default: false },
  ],
  exampleIdeas: [
    'SQL injection in a login form with WAF bypass using double encoding',
    'Server-side template injection in a Jinja2 email template generator',
    'Insecure deserialization in a Java Spring session cookie',
  ],
  promptHints: 'Focus on realistic web application scenarios. Include Dockerfile for isolated deployment. Vulnerable endpoints should be discoverable through enumeration.',
  builder: true,
};
