export default {
  id: 'network',
  name: 'Network',
  description: 'Packet analysis, protocol exploitation, traffic decryption, network reconnaissance, and infrastructure attacks.',
  icon: 'wifi',
  color: '#57cbff',
  defaultTechStack: ['Python', 'Scapy', 'Wireshark', 'Docker'],
  difficulties: [
    { level: 'warm_up', points: [50], estimatedMinutes: 10, description: 'Follow the stream, plaintext flag' },
    { level: 'easy', points: [150], estimatedMinutes: 20, description: 'Basic packet analysis, plaintext credentials' },
    { level: 'medium', points: [350], estimatedMinutes: 45, description: 'Protocol-specific exploits, encrypted traffic' },
    { level: 'hard', points: [700], estimatedMinutes: 90, description: 'Custom protocols, covert channels, traffic manipulation' },
  ],
  artifactTypes: ['PCAP generator', 'Network capture', 'Topology diagram', 'Solver script', 'Writeup'],
  outputFiles: ['generate_pcap.py', 'capture.pcap', 'network_topology.txt', 'solve.py', 'writeup.md'],
  difficultyWeights: { warm_up: 50, easy: 150, medium: 350, hard: 700 },
  supportsDocker: true,
  formFields: [
    { name: 'protocol', label: 'Target Protocol', type: 'select', options: ['HTTP/HTTPS', 'DNS', 'TCP/UDP', 'FTP', 'SMB', 'SSH', 'ICMP', 'Custom Protocol', 'Other'] },
    { name: 'attackType', label: 'Network Attack', type: 'select', options: ['Packet Analysis', 'Traffic Decryption', 'Covert Channel', 'ARP Spoofing', 'DNS Hijacking', 'Protocol Exploitation', 'Credential Sniffing', 'Other'] },
    { name: 'includeTopology', label: 'Include Network Topology', type: 'checkbox', default: false },
  ],
  exampleIdeas: [
    'Analyze PCAP to detect HTTP/2 Rapid Reset attack patterns and extract the C2 server address',
    'Decrypt TLS traffic using a leaked session key to find exfiltrated data',
    'Identify covert DNS tunneling channel hiding data in CNAME record responses',
  ],
  promptHints: 'Generate realistic PCAP files with believable background traffic. Hide challenge data within protocol-specific fields. Include network topology diagrams when relevant.',
  builder: true,
};
