/**
 * Cryptography — category-specific builder.
 * Mock implementation that uses the REAL spec data (flag, name, exploit path).
 * Phase 3: will call Claude API with prompt.md like web/forensics builders.
 */
export default {
  categoryId: 'crypto',

  async build(spec) {
    const name = spec.challengeName || spec.challenge_name || 'Crypto Challenge';
    const flag = spec.flag || (Array.isArray(spec.flags) && spec.flags[0]) || null;
    if (!flag) throw new Error('Crypto builder: spec has no flag');

    const narrative = spec.narrative || 'Break the cryptographic scheme.';
    const difficulty = spec.difficulty || 'medium';
    const points = spec.points || 300;
    const exploitPath = spec.exploitPath || ['Analyze the encryption', 'Find the weakness', 'Decrypt the flag'];
    const techStack = spec.techStack || ['Python', 'PyCryptodome'];
    const antiAi = spec.antiAiCountermeasures || [];

    return {
      files: [
        {
          path: 'encrypt.py',
          language: 'python',
          content: `#!/usr/bin/env python3
"""${name} - Encryption Script"""
# Tech stack: ${techStack.join(', ')}
# Difficulty: ${difficulty}
import os, base64

FLAG = "${flag}"

# TODO: Phase 3 will generate a real crypto challenge matching the spec
# Exploit path:
${exploitPath.map((s, i) => `#   ${i + 1}. ${s}`).join('\n')}

def encrypt(plaintext):
    """Placeholder encryption — Phase 3 will implement real crypto"""
    key = os.urandom(16)
    ct = bytes([p ^ k for p, k in zip(plaintext.encode(), key * (len(plaintext) // len(key) + 1))])
    return base64.b64encode(ct).decode(), base64.b64encode(key).decode()

if __name__ == "__main__":
    ciphertext, key_hint = encrypt(FLAG)
    with open("ciphertext.txt", "w") as f:
        f.write(ciphertext)
    with open("key_fragment.txt", "w") as f:
        f.write(key_hint[:8] + "...")
    print("[+] Challenge files generated")
`,
        },
        {
          path: 'ciphertext.txt',
          language: 'text',
          content: '[ Generated by encrypt.py — run the script to create this file ]',
        },
        {
          path: 'solve.py',
          language: 'python',
          content: `#!/usr/bin/env python3
"""Solver for ${name}"""
${exploitPath.map((s, i) => `# Step ${i + 1}: ${s}`).join('\n')}

print("[*] Running crypto solver...")
${exploitPath.map((s, i) => `print("[*] Step ${i + 1}: ${s}")`).join('\n')}
print(f"[+] Flag: ${flag}")
`,
        },
        {
          path: 'writeup.md',
          language: 'markdown',
          content: `# ${name} - Writeup

## Challenge Description
${narrative}

## Difficulty
${difficulty} (${points} points)

## Tech Stack
${techStack.map((t) => `- ${t}`).join('\n')}

## Solution
${exploitPath.map((s, i) => `${i + 1}. ${s}`).join('\n')}
${antiAi.length > 0 ? `\n## Anti-AI Measures\n${antiAi.map((m) => `- ${m}`).join('\n')}\n` : ''}
## Flag
\`${flag}\`
`,
        },
      ],
      tokenUsage: 0,
      durationMs: 0,
    };
  },
};
